"""Added cancel part

Revision ID: 6f48b3525ee6
Revises: c81bac34faab
Create Date: 2019-03-05 05:02:24.635553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f48b3525ee6'
down_revision = 'c81bac34faab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('cancelled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'cancelled')
    # ### end Alembic commands ###
